#pragma once

struct Settings
{
	using ISetting = AutoTOML::ISetting;
	using bSetting = AutoTOML::bSetting;
	using sSetting = AutoTOML::sSetting;
	using iSetting = AutoTOML::iSetting;

	static void load() {
		try {
			const auto table = toml::parse_file("Data/SKSE/Plugins/ShowStats.toml"s);
			for (const auto& setting : ISetting::get_settings()) {
				setting->load(table);
			}
		} catch (const toml::parse_error& ex) {
			std::ostringstream ss;
			ss << "Error parsing file \'" << *ex.source().path << "\':\n"
			   << '\t' << ex.description() << '\n'
			   << "\t\t(" << ex.source().begin << ')';
			logger::error(ss.str());
			throw std::runtime_error("failed to load settings"s);
		}
	}

	static inline bSetting name{ "showStats"s, "name"s, true };
	static inline bSetting race{ "showStats"s, "race"s, true };
	static inline bSetting level{ "showStats"s, "level"s, true };
	static inline bSetting perkCount{ "showStats"s, "perkCount"s, true };
	static inline bSetting height{ "showStats"s, "height"s, true };
	static inline bSetting equipedWeight{ "showStats"s, "equipedWeight"s, true };
	static inline bSetting weight{ "showStats"s, "weight"s, true };
	static inline bSetting armor{ "showStats"s, "armor"s, true };
	static inline bSetting damage{ "showStats"s, "damage"s, true };
	static inline bSetting skillTrainingsThisLevel{ "showStats"s, "skillTrainingsThisLevel"s, true };
	static inline bSetting health{ "showStats"s, "health"s, true };
	static inline bSetting healthRate{ "showStats"s, "healthRatePer"s, true };
	static inline bSetting magicka{ "showStats"s, "magicka"s, true };
	static inline bSetting magickaRate{ "showStats"s, "magickaRatePer"s, true };
	static inline bSetting stamina{ "showStats"s, "stamina"s, true };
	static inline bSetting staminaRate{ "showStats"s, "staminaRatePer"s, true };
	static inline bSetting resistDamage{ "showStats"s, "resistDamage"s, true };
	static inline bSetting resistDisease{ "showStats"s, "resistDisease"s, true };
	static inline bSetting resistPoison{ "showStats"s, "resistPoison"s, true };
	static inline bSetting resistFire{ "showStats"s, "resistFire"s, true };
	static inline bSetting resistShock{ "showStats"s, "resistShock"s, true };
	static inline bSetting resistFrost{ "showStats"s, "resistFrost"s, true };
	static inline bSetting resistMagic{ "showStats"s, "resistMagic"s, true };
	static inline bSetting oneHanded{ "showStats"s, "oneHanded"s, true };
	static inline bSetting twoHanded{ "showStats"s, "twoHanded"s, true };
	static inline bSetting archery{ "showStats"s, "archery"s, true };
	static inline bSetting block{ "showStats"s, "block"s, true };
	static inline bSetting smithing{ "showStats"s, "smithing"s, true };
	static inline bSetting heavyArmor{ "showStats"s, "heavyArmor"s, true };
	static inline bSetting lightArmor{ "showStats"s, "lightArmor"s, true };
	static inline bSetting pickpocket{ "showStats"s, "pickpocket"s, true };
	static inline bSetting lockpicking{ "showStats"s, "lockpicking"s, true };
	static inline bSetting sneak{ "showStats"s, "sneak"s, true };
	static inline bSetting alchemy{ "showStats"s, "alchemy"s, true };
	static inline bSetting speech{ "showStats"s, "speech"s, true };
	static inline bSetting enchanting{ "showStats"s, "enchanting"s, true };
	static inline bSetting alteration{ "showStats"s, "alteration"s, true };
	static inline bSetting conjuration{ "showStats"s, "conjuration"s, true };
	static inline bSetting destruction{ "showStats"s, "destruction"s, true };
	static inline bSetting illusion{ "showStats"s, "illusion"s, true };
	static inline bSetting restoration{ "showStats"s, "restoration"s, true };
	static inline bSetting oneHandedPowerMod{ "showStats"s, "oneHandedPowerMod"s, true };
	static inline bSetting twoHandedPowerMod{ "showStats"s, "twoHandedPowerMod"s, true };
	static inline bSetting archeryPowerMod{ "showStats"s, "archeryPowerMod"s, true };
	static inline bSetting blockPowerMod{ "showStats"s, "blockPowerMod"s, true };
	static inline bSetting smithingPowerMod{ "showStats"s, "smithingPowerMod"s, true };
	static inline bSetting heavyArmorPowerMod{ "showStats"s, "heavyArmorPowerMod"s, true };
	static inline bSetting lightArmorPowerMod{ "showStats"s, "lightArmorPowerMod"s, true };
	static inline bSetting pickpocketPowerMod{ "showStats"s, "pickpocketPowerMod"s, true };
	static inline bSetting lockpickingPowerMod{ "showStats"s, "lockpickingPowerMod"s, true };
	static inline bSetting sneakPowerMod{ "showStats"s, "sneakPowerMod"s, true };
	static inline bSetting alchemyPowerMod{ "showStats"s, "alchemyPowerMod"s, true };
	static inline bSetting speechPowerMod{ "showStats"s, "speechPowerMod"s, true };
	static inline bSetting enchantingPowerMod{ "showStats"s, "enchantingPowerMod"s, true };
	static inline bSetting alterationPowerMod{ "showStats"s, "alterationPowerMod"s, true };
	static inline bSetting conjurationPowerMod{ "showStats"s, "conjurationPowerMod"s, true };
	static inline bSetting destructionPowerMod{ "showStats"s, "destructionPowerMod"s, true };
	static inline bSetting illusionPowerMod{ "showStats"s, "illusionPowerMod"s, true };
	static inline bSetting restorationPowerMod{ "showStats"s, "restorationPowerMod"s, true };
	static inline bSetting speedMult{ "showStats"s, "speedMult"s, true };
	static inline bSetting inventoryWeight{ "showStats"s, "inventoryWeight"s, true };
	static inline bSetting carryWeight{ "showStats"s, "carryWeight"s, true };
	static inline bSetting criticalChance{ "showStats"s, "criticalChance"s, true };
	static inline bSetting meleeDamage{ "showStats"s, "meleeDamage"s, true };
	static inline bSetting unarmedDamage{ "showStats"s, "unarmedDamage"s, true };
	static inline bSetting absorbChance{ "showStats"s, "absorbChance"s, true };
	static inline bSetting weaponSpeedMult{ "showStats"s, "weaponSpeedMult"s, true };
	static inline bSetting bowSpeedBonus{ "showStats"s, "bowSpeedBonus"s, true };
	static inline bSetting shoutRecoveryMult{ "showStats"s, "shoutRecoveryMult"s, true };
	static inline bSetting movementNoiseMult{ "showStats"s, "movementNoiseMult"s, true };
	static inline bSetting dragonSouls{ "showStats"s, "dragonSouls"s, true };
	static inline bSetting combatHealthRegenMultiply{ "showStats"s, "combatHealthRegenMultiply"s, true };
	static inline bSetting attackDamageMult{ "showStats"s, "attackDamageMult"s, true };
	static inline bSetting beast{ "showStats"s, "beast"s, true };
	static inline bSetting xp{ "showStats"s, "xp"s, true };
	static inline bSetting reflectDamage{ "showStats"s, "reflectDamage"s, true };
	static inline bSetting oneHandedMod{ "showStats"s, "oneHandedMod"s, true };
	static inline bSetting twoHandedMod{ "showStats"s, "twoHandedMod"s, true };
	static inline bSetting archeryMod{ "showStats"s, "archeryMod"s, true };
	static inline bSetting blockMod{ "showStats"s, "blockMod"s, true };
	static inline bSetting smithingMod{ "showStats"s, "smithingMod"s, true };
	static inline bSetting heavyArmorMod{ "showStats"s, "heavyArmorMod"s, true };
	static inline bSetting lightArmorMod{ "showStats"s, "lightArmorMod"s, true };
	static inline bSetting pickpocketMod{ "showStats"s, "pickpocketMod"s, true };
	static inline bSetting lockpickingMod{ "showStats"s, "lockpickingMod"s, true };
	static inline bSetting sneakMod{ "showStats"s, "sneakMod"s, true };
	static inline bSetting alchemyMod{ "showStats"s, "alchemyMod"s, true };
	static inline bSetting speechMod{ "showStats"s, "speechMod"s, true };
	static inline bSetting enchantingMod{ "showStats"s, "enchantingMod"s, true };
	static inline bSetting alterationMod{ "showStats"s, "alterationMod"s, true };
	static inline bSetting conjurationMod{ "showStats"s, "conjurationMod"s, true };
	static inline bSetting destructionMod{ "showStats"s, "destructionMod"s, true };
	static inline bSetting illusionMod{ "showStats"s, "illusionMod"s, true };
	static inline bSetting restorationMod{ "showStats"s, "restorationMod"s, true };
	static inline bSetting damageArrow{ "showStats"s, "damageArrow"s, true };
	static inline bSetting damageRight{ "showStats"s, "damageRight"s, true };
	static inline bSetting damageLeft{ "showStats"s, "damageLeft"s, true };

	static inline sSetting nameString { "showStatsName"s, "name"s, "<undef>" };
	static inline sSetting raceString { "showStatsName"s, "race"s, "<undef>" };
	static inline sSetting levelString { "showStatsName"s, "level"s, "<undef>" };
	static inline sSetting perkCountString{ "showStatsName"s, "perkCount"s, "<undef>" };
	static inline sSetting heightString{ "showStatsName"s, "height"s, "<undef>" };
	static inline sSetting equipedWeightString{ "showStatsName"s, "equipedWeight"s, "<undef>" };
	static inline sSetting weightString{ "showStatsName"s, "weight"s, "<undef>" };
	static inline sSetting armorString{ "showStatsName"s, "armor"s, "<undef>" };
	static inline sSetting damageString{ "showStatsName"s, "damage"s, "<undef>" };
	static inline sSetting skillTrainingsThisLevelString{ "showStatsName"s, "skillTrainingsThisLevel"s, "<undef>" };
	static inline sSetting healthString{ "showStatsName"s, "health"s, "<undef>" };
	static inline sSetting healthRateString{ "showStatsName"s, "healthRatePer"s, "<undef>" };
	static inline sSetting magickaString{ "showStatsName"s, "magicka"s, "<undef>" };
	static inline sSetting magickaRateString{ "showStatsName"s, "magickaRatePer"s, "<undef>" };
	static inline sSetting staminaString{ "showStatsName"s, "stamina"s, "<undef>" };
	static inline sSetting staminaRateString{ "showStatsName"s, "staminaRatePer"s, "<undef>" };
	static inline sSetting resistDamageString{ "showStatsName"s, "resistDamage"s, "<undef>" };
	static inline sSetting resistDiseaseString{ "showStatsName"s, "resistDisease"s, "<undef>" };
	static inline sSetting resistPoisonString{ "showStatsName"s, "resistPoison"s, "<undef>" };
	static inline sSetting resistFireString{ "showStatsName"s, "resistFire"s, "<undef>" };
	static inline sSetting resistShockString{ "showStatsName"s, "resistShock"s, "<undef>" };
	static inline sSetting resistFrostString{ "showStatsName"s, "resistFrost"s, "<undef>" };
	static inline sSetting resistMagicString{ "showStatsName"s, "resistMagic"s, "<undef>" };
	static inline sSetting oneHandedString{ "showStatsName"s, "oneHanded"s, "<undef>" };
	static inline sSetting twoHandedString{ "showStatsName"s, "twoHanded"s, "<undef>" };
	static inline sSetting archeryString{ "showStatsName"s, "archery"s, "<undef>" };
	static inline sSetting blockString{ "showStatsName"s, "block"s, "<undef>" };
	static inline sSetting smithingString{ "showStatsName"s, "smithing"s, "<undef>" };
	static inline sSetting heavyArmorString{ "showStatsName"s, "heavyArmor"s, "<undef>" };
	static inline sSetting lightArmorString{ "showStatsName"s, "lightArmor"s, "<undef>" };
	static inline sSetting pickpocketString{ "showStatsName"s, "pickpocket"s, "<undef>" };
	static inline sSetting lockpickingString{ "showStatsName"s, "lockpicking"s, "<undef>" };
	static inline sSetting sneakString{ "showStatsName"s, "sneak"s, "<undef>" };
	static inline sSetting alchemyString{ "showStatsName"s, "alchemy"s, "<undef>" };
	static inline sSetting speechString{ "showStatsName"s, "speech"s, "<undef>" };
	static inline sSetting enchantingString{ "showStatsName"s, "enchanting"s, "<undef>" };
	static inline sSetting alterationString{ "showStatsName"s, "alteration"s, "<undef>" };
	static inline sSetting conjurationString{ "showStatsName"s, "conjuration"s, "<undef>" };
	static inline sSetting destructionString{ "showStatsName"s, "destruction"s, "<undef>" };
	static inline sSetting illusionString{ "showStatsName"s, "illusion"s, "<undef>" };
	static inline sSetting restorationString{ "showStatsName"s, "restoration"s, "<undef>" };
	static inline sSetting oneHandedPowerModString{ "showStatsName"s, "oneHandedPowerMod"s, "<undef>" };
	static inline sSetting twoHandedPowerModString{ "showStatsName"s, "twoHandedPowerMod"s, "<undef>" };
	static inline sSetting archeryPowerModString{ "showStatsName"s, "archeryPowerMod"s, "<undef>" };
	static inline sSetting blockPowerModString{ "showStatsName"s, "blockPowerMod"s, "<undef>" };
	static inline sSetting smithingPowerModString{ "showStatsName"s, "smithingPowerMod"s, "<undef>" };
	static inline sSetting heavyArmorPowerModString{ "showStatsName"s, "heavyArmorPowerMod"s, "<undef>" };
	static inline sSetting lightArmorPowerModString{ "showStatsName"s, "lightArmorPowerMod"s, "<undef>" };
	static inline sSetting pickpocketPowerModString{ "showStatsName"s, "pickpocketPowerMod"s, "<undef>" };
	static inline sSetting lockpickingPowerModString{ "showStatsName"s, "lockpickingPowerMod"s, "<undef>" };
	static inline sSetting sneakPowerModString{ "showStatsName"s, "sneakPowerMod"s, "<undef>" };
	static inline sSetting alchemyPowerModString{ "showStatsName"s, "alchemyPowerMod"s, "<undef>" };
	static inline sSetting speechPowerModString{ "showStatsName"s, "speechPowerMod"s, "<undef>" };
	static inline sSetting enchantingPowerModString{ "showStatsName"s, "enchantingPowerMod"s, "<undef>" };
	static inline sSetting alterationPowerModString{ "showStatsName"s, "alterationPowerMod"s, "<undef>" };
	static inline sSetting conjurationPowerModString{ "showStatsName"s, "conjurationPowerMod"s, "<undef>" };
	static inline sSetting destructionPowerModString{ "showStatsName"s, "destructionPowerMod"s, "<undef>" };
	static inline sSetting illusionPowerModString{ "showStatsName"s, "illusionPowerMod"s, "<undef>" };
	static inline sSetting restorationPowerModString{ "showStatsName"s, "restorationPowerMod"s, "<undef>" };
	static inline sSetting speedMultString{ "showStatsName"s, "speedMult"s, "<undef>" };
	static inline sSetting inventoryWeightString{ "showStatsName"s, "inventoryWeight"s, "<undef>" };
	static inline sSetting carryWeightString{ "showStatsName"s, "carryWeight"s, "<undef>" };
	static inline sSetting criticalChanceString{ "showStatsName"s, "criticalChance"s, "<undef>" };
	static inline sSetting meleeDamageString{ "showStatsName"s, "meleeDamage"s, "<undef>" };
	static inline sSetting unarmedDamageString{ "showStatsName"s, "unarmedDamage"s, "<undef>" };
	static inline sSetting absorbChanceString{ "showStatsName"s, "absorbChance"s, "<undef>" };
	static inline sSetting weaponSpeedMultString{ "showStatsName"s, "weaponSpeedMult"s, "<undef>" };
	static inline sSetting bowSpeedBonusString{ "showStatsName"s, "bowSpeedBonus"s, "<undef>" };
	static inline sSetting shoutRecoveryMultString{ "showStatsName"s, "shoutRecoveryMult"s, "<undef>" };
	static inline sSetting movementNoiseMultString{ "showStatsName"s, "movementNoiseMult"s, "<undef>" };
	static inline sSetting dragonSoulsString{ "showStatsName"s, "dragonSouls"s, "<undef>" };
	static inline sSetting combatHealthRegenMultiplyString{ "showStatsName"s, "combatHealthRegenMultiply"s, "<undef>" };
	static inline sSetting attackDamageMultString{ "showStatsName"s, "attackDamageMult"s, "<undef>" };
	static inline sSetting beastString{ "showStatsName"s, "beast"s, "<undef>" };
	static inline sSetting xpString{ "showStatsName"s, "xp"s, "<undef>" };
	static inline sSetting reflectDamageString{ "showStatsName"s, "reflectDamage"s, "<undef>" };
	static inline sSetting oneHandedModString{ "showStatsName"s, "oneHandedMod"s, "<undef>" };
	static inline sSetting twoHandedModString{ "showStatsName"s, "twoHandedMod"s, "<undef>" };
	static inline sSetting archeryModString{ "showStatsName"s, "archeryMod"s, "<undef>" };
	static inline sSetting blockModString{ "showStatsName"s, "blockMod"s, "<undef>" };
	static inline sSetting smithingModString{ "showStatsName"s, "smithingMod"s, "<undef>" };
	static inline sSetting heavyArmorModString{ "showStatsName"s, "heavyArmorMod"s, "<undef>" };
	static inline sSetting lightArmorModString{ "showStatsName"s, "lightArmorMod"s, "<undef>" };
	static inline sSetting pickpocketModString{ "showStatsName"s, "pickpocketMod"s, "<undef>" };
	static inline sSetting lockpickingModString{ "showStatsName"s, "lockpickingMod"s, "<undef>" };
	static inline sSetting sneakModString{ "showStatsName"s, "sneakMod"s, "<undef>" };
	static inline sSetting alchemyModString{ "showStatsName"s, "alchemyMod"s, "<undef>" };
	static inline sSetting speechModString{ "showStatsName"s, "speechMod"s, "<undef>" };
	static inline sSetting enchantingModString{ "showStatsName"s, "enchantingMod"s, "<undef>" };
	static inline sSetting alterationModString{ "showStatsName"s, "alterationMod"s, "<undef>" };
	static inline sSetting conjurationModString{ "showStatsName"s, "conjurationMod"s, "<undef>" };
	static inline sSetting destructionModString{ "showStatsName"s, "destructionMod"s, "<undef>" };
	static inline sSetting illusionModString{ "showStatsName"s, "illusionMod"s, "<undef>" };
	static inline sSetting restorationModString{ "showStatsName"s, "restorationMod"s, "<undef>" };
	static inline sSetting damageArrowString{ "showStatsName"s, "damageArrow"s, "<undef>" };
	static inline sSetting damageRightString{ "showStatsName"s, "damageRight"s, "<undef>" };
	static inline sSetting damageLeftString{ "showStatsName"s, "damageLeft"s, "<undef>" };

	static inline sSetting nameStringEnding{ "showStatsEnding"s, "name"s, "<undef>" };
	static inline sSetting raceStringEnding{ "showStatsEnding"s, "race"s, "<undef>" };
	static inline sSetting levelStringEnding{ "showStatsEnding"s, "level"s, "<undef>" };
	static inline sSetting perkCountStringEnding{ "showStatsEnding"s, "perkCount"s, "<undef>" };
	static inline sSetting heightStringEnding{ "showStatsEnding"s, "height"s, "<undef>" };
	static inline sSetting equipedWeightStringEnding{ "showStatsEnding"s, "equipedWeight"s, "<undef>" };
	static inline sSetting weightStringEnding{ "showStatsEnding"s, "weight"s, "<undef>" };
	static inline sSetting armorStringEnding{ "showStatsEnding"s, "armor"s, "<undef>" };
	static inline sSetting damageStringEnding{ "showStatsEnding"s, "damage"s, "<undef>" };
	static inline sSetting skillTrainingsThisLevelStringEnding{ "showStatsEnding"s, "skillTrainingsThisLevel"s, "<undef>" };
	static inline sSetting healthStringEnding{ "showStatsEnding"s, "health"s, "<undef>" };
	static inline sSetting healthRateStringEnding{ "showStatsEnding"s, "healthRatePer"s, "<undef>" };
	static inline sSetting magickaStringEnding{ "showStatsEnding"s, "magicka"s, "<undef>" };
	static inline sSetting magickaRateStringEnding{ "showStatsEnding"s, "magickaRatePer"s, "<undef>" };
	static inline sSetting staminaStringEnding{ "showStatsEnding"s, "stamina"s, "<undef>" };
	static inline sSetting staminaRateStringEnding{ "showStatsEnding"s, "staminaRatePer"s, "<undef>" };
	static inline sSetting resistDamageStringEnding{ "showStatsEnding"s, "resistDamage"s, "<undef>" };
	static inline sSetting resistDiseaseStringEnding{ "showStatsEnding"s, "resistDisease"s, "<undef>" };
	static inline sSetting resistPoisonStringEnding{ "showStatsEnding"s, "resistPoison"s, "<undef>" };
	static inline sSetting resistFireStringEnding{ "showStatsEnding"s, "resistFire"s, "<undef>" };
	static inline sSetting resistShockStringEnding{ "showStatsEnding"s, "resistShock"s, "<undef>" };
	static inline sSetting resistFrostStringEnding{ "showStatsEnding"s, "resistFrost"s, "<undef>" };
	static inline sSetting resistMagicStringEnding{ "showStatsEnding"s, "resistMagic"s, "<undef>" };
	static inline sSetting oneHandedStringEnding{ "showStatsEnding"s, "oneHanded"s, "<undef>" };
	static inline sSetting twoHandedStringEnding{ "showStatsEnding"s, "twoHanded"s, "<undef>" };
	static inline sSetting archeryStringEnding{ "showStatsEnding"s, "archery"s, "<undef>" };
	static inline sSetting blockStringEnding{ "showStatsEnding"s, "block"s, "<undef>" };
	static inline sSetting smithingStringEnding{ "showStatsEnding"s, "smithing"s, "<undef>" };
	static inline sSetting heavyArmorStringEnding{ "showStatsEnding"s, "heavyArmor"s, "<undef>" };
	static inline sSetting lightArmorStringEnding{ "showStatsEnding"s, "lightArmor"s, "<undef>" };
	static inline sSetting pickpocketStringEnding{ "showStatsEnding"s, "pickpocket"s, "<undef>" };
	static inline sSetting lockpickingStringEnding{ "showStatsEnding"s, "lockpicking"s, "<undef>" };
	static inline sSetting sneakStringEnding{ "showStatsEnding"s, "sneak"s, "<undef>" };
	static inline sSetting alchemyStringEnding{ "showStatsEnding"s, "alchemy"s, "<undef>" };
	static inline sSetting speechStringEnding{ "showStatsEnding"s, "speech"s, "<undef>" };
	static inline sSetting enchantingStringEnding{ "showStatsEnding"s, "enchanting"s, "<undef>" };
	static inline sSetting alterationStringEnding{ "showStatsEnding"s, "alteration"s, "<undef>" };
	static inline sSetting conjurationStringEnding{ "showStatsEnding"s, "conjuration"s, "<undef>" };
	static inline sSetting destructionStringEnding{ "showStatsEnding"s, "destruction"s, "<undef>" };
	static inline sSetting illusionStringEnding{ "showStatsEnding"s, "illusion"s, "<undef>" };
	static inline sSetting restorationStringEnding{ "showStatsEnding"s, "restoration"s, "<undef>" };
	static inline sSetting oneHandedPowerModStringEnding{ "showStatsEnding"s, "oneHandedPowerMod"s, "<undef>" };
	static inline sSetting twoHandedPowerModStringEnding{ "showStatsEnding"s, "twoHandedPowerMod"s, "<undef>" };
	static inline sSetting archeryPowerModStringEnding{ "showStatsEnding"s, "archeryPowerMod"s, "<undef>" };
	static inline sSetting blockPowerModStringEnding{ "showStatsEnding"s, "blockPowerMod"s, "<undef>" };
	static inline sSetting smithingPowerModStringEnding{ "showStatsEnding"s, "smithingPowerMod"s, "<undef>" };
	static inline sSetting heavyArmorPowerModStringEnding{ "showStatsEnding"s, "heavyArmorPowerMod"s, "<undef>" };
	static inline sSetting lightArmorPowerModStringEnding{ "showStatsEnding"s, "lightArmorPowerMod"s, "<undef>" };
	static inline sSetting pickpocketPowerModStringEnding{ "showStatsEnding"s, "pickpocketPowerMod"s, "<undef>" };
	static inline sSetting lockpickingPowerModStringEnding{ "showStatsEnding"s, "lockpickingPowerMod"s, "<undef>" };
	static inline sSetting sneakPowerModStringEnding{ "showStatsEnding"s, "sneakPowerMod"s, "<undef>" };
	static inline sSetting alchemyPowerModStringEnding{ "showStatsEnding"s, "alchemyPowerMod"s, "<undef>" };
	static inline sSetting speechPowerModStringEnding{ "showStatsEnding"s, "speechPowerMod"s, "<undef>" };
	static inline sSetting enchantingPowerModStringEnding{ "showStatsEnding"s, "enchantingPowerMod"s, "<undef>" };
	static inline sSetting alterationPowerModStringEnding{ "showStatsEnding"s, "alterationPowerMod"s, "<undef>" };
	static inline sSetting conjurationPowerModStringEnding{ "showStatsEnding"s, "conjurationPowerMod"s, "<undef>" };
	static inline sSetting destructionPowerModStringEnding{ "showStatsEnding"s, "destructionPowerMod"s, "<undef>" };
	static inline sSetting illusionPowerModStringEnding{ "showStatsEnding"s, "illusionPowerMod"s, "<undef>" };
	static inline sSetting restorationPowerModStringEnding{ "showStatsEnding"s, "restorationPowerMod"s, "<undef>" };
	static inline sSetting speedMultStringEnding{ "showStatsEnding"s, "speedMult"s, "<undef>" };
	static inline sSetting inventoryWeightStringEnding{ "showStatsEnding"s, "inventoryWeight"s, "<undef>" };
	static inline sSetting carryWeightStringEnding{ "showStatsEnding"s, "carryWeight"s, "<undef>" };
	static inline sSetting criticalChanceStringEnding{ "showStatsEnding"s, "criticalChance"s, "<undef>" };
	static inline sSetting meleeDamageStringEnding{ "showStatsEnding"s, "meleeDamage"s, "<undef>" };
	static inline sSetting unarmedDamageStringEnding{ "showStatsEnding"s, "unarmedDamage"s, "<undef>" };
	static inline sSetting absorbChanceStringEnding{ "showStatsEnding"s, "absorbChance"s, "<undef>" };
	static inline sSetting weaponSpeedMultStringEnding{ "showStatsEnding"s, "weaponSpeedMult"s, "<undef>" };
	static inline sSetting bowSpeedBonusStringEnding{ "showStatsEnding"s, "bowSpeedBonus"s, "<undef>" };
	static inline sSetting shoutRecoveryMultStringEnding{ "showStatsEnding"s, "shoutRecoveryMult"s, "<undef>" };
	static inline sSetting movementNoiseMultStringEnding{ "showStatsEnding"s, "movementNoiseMult"s, "<undef>" };
	static inline sSetting dragonSoulsStringEnding{ "showStatsEnding"s, "dragonSouls"s, "<undef>" };
	static inline sSetting combatHealthRegenMultiplyStringEnding{ "showStatsEnding"s, "combatHealthRegenMultiply"s, "<undef>" };
	static inline sSetting attackDamageMultStringEnding{ "showStatsEnding"s, "attackDamageMult"s, "<undef>" };
	static inline sSetting beastStringEnding{ "showStatsEnding"s, "beast"s, "<undef>" };
	static inline sSetting xpStringEnding{ "showStatsEnding"s, "xp"s, "<undef>" };
	static inline sSetting reflectDamageStringEnding{ "showStatsEnding"s, "reflectDamage"s, "<undef>" };
	static inline sSetting oneHandedModStringEnding{ "showStatsEnding"s, "oneHandedMod"s, "<undef>" };
	static inline sSetting twoHandedModStringEnding{ "showStatsEnding"s, "twoHandedMod"s, "<undef>" };
	static inline sSetting archeryModStringEnding{ "showStatsEnding"s, "archeryMod"s, "<undef>" };
	static inline sSetting blockModStringEnding{ "showStatsEnding"s, "blockMod"s, "<undef>" };
	static inline sSetting smithingModStringEnding{ "showStatsEnding"s, "smithingMod"s, "<undef>" };
	static inline sSetting heavyArmorModStringEnding{ "showStatsEnding"s, "heavyArmorMod"s, "<undef>" };
	static inline sSetting lightArmorModStringEnding{ "showStatsEnding"s, "lightArmorMod"s, "<undef>" };
	static inline sSetting pickpocketModStringEnding{ "showStatsEnding"s, "pickpocketMod"s, "<undef>" };
	static inline sSetting lockpickingModStringEnding{ "showStatsEnding"s, "lockpickingMod"s, "<undef>" };
	static inline sSetting sneakModStringEnding{ "showStatsEnding"s, "sneakMod"s, "<undef>" };
	static inline sSetting alchemyModStringEnding{ "showStatsEnding"s, "alchemyMod"s, "<undef>" };
	static inline sSetting speechModStringEnding{ "showStatsEnding"s, "speechMod"s, "<undef>" };
	static inline sSetting enchantingModStringEnding{ "showStatsEnding"s, "enchantingMod"s, "<undef>" };
	static inline sSetting alterationModStringEnding{ "showStatsEnding"s, "alterationMod"s, "<undef>" };
	static inline sSetting conjurationModStringEnding{ "showStatsEnding"s, "conjurationMod"s, "<undef>" };
	static inline sSetting destructionModStringEnding{ "showStatsEnding"s, "destructionMod"s, "<undef>" };
	static inline sSetting illusionModStringEnding{ "showStatsEnding"s, "illusionMod"s, "<undef>" };
	static inline sSetting restorationModStringEnding{ "showStatsEnding"s, "restorationMod"s, "<undef>" };
	static inline sSetting damageArrowStringEnding{ "showStatsEnding"s, "damageArrow"s, "<undef>" };
	static inline sSetting damageRightStringEnding{ "showStatsEnding"s, "damageRight"s, "<undef>" };
	static inline sSetting damageLeftStringEnding{ "showStatsEnding"s, "damageLeft"s, "<undef>" };

	static inline iSetting logLevel{"General"s, "logLevel"s, 0};
	static inline bSetting closeOnEveryButtonPress{ "General"s, "closeOnEveryButtonPress", true };

	static inline sSetting vampireString{ "showBeastName"s, "vampire"s, "<undef>" };
	static inline sSetting werewolfString{ "showBeastName"s, "werewolf"s, "<undef>" };
};