set(headers ${headers}
	include/CLIK/Array.h
	include/CLIK/GFx/Controls/Button.h
	include/CLIK/GFx/Controls/ButtonBar.h
	include/CLIK/GFx/Controls/CoreList.h
	include/CLIK/GFx/Controls/DropdownMenu.h
	include/CLIK/GFx/Controls/ScrollingList.h
	include/CLIK/GFx/Controls/Slider.h
	include/CLIK/GFx/Controls/TextInput.h
	include/CLIK/GFx/Core/UIComponent.h
	include/CLIK/MovieClip.h
	include/CLIK/Object.h
	include/CLIK/TextField.h
	include/Events.h
	include/PCH.h
	include/constants.h
	include/data/factiondata.h
	include/data/playerdata.h
	include/hooks.h
	include/papyrus.h
	include/scaleform/factionmenu.h
	include/scaleform/scaleform.h
	include/scaleform/statsmenu.h
	include/serialhelper.h
	include/settings/settings.h
	include/showhandler.h
	include/stats/champion.h
	include/stats/faction.h
	include/stats/factionfiller.h
	include/stats/factionholder.h
	include/stats/statfiller.h
	include/stats/statholder.h
	include/stats/thane.h
	include/utils.h
)
