set(sources ${sources}
	src/CLIK/Array.h
	src/CLIK/GFx/Controls/Button.h
	src/CLIK/GFx/Controls/CoreList.h
	src/CLIK/GFx/Controls/ScrollingList.h
	src/CLIK/GFx/Core/UIComponent.h
	src/CLIK/MovieClip.h
	src/CLIK/Object.h
	src/CLIK/TextField.h
	src/PCH.h
	src/actor/champion.cpp
	src/actor/champion.h
	src/actor/faction.cpp
	src/actor/faction.h
	src/actor/player.cpp
	src/actor/player.h
	src/actor/thane.cpp
	src/actor/thane.h
	src/event/equip_event.cpp
	src/event/equip_event.h
	src/event/event.cpp
	src/event/event.h
	src/event/input_event.cpp
	src/event/input_event.h
	src/event/menu_open_close_event.cpp
	src/event/menu_open_close_event.h
	src/main.cpp
	src/mod/armor_rating_rescaled_remake.cpp
	src/mod/armor_rating_rescaled_remake.h
	src/mod/blade_and_blunt.cpp
	src/mod/blade_and_blunt.h
	src/mod/mod_manager.cpp
	src/mod/mod_manager.h
	src/scaleform/menus/faction_menu.cpp
	src/scaleform/menus/faction_menu.h
	src/scaleform/menus/stats_inventory_menu.cpp
	src/scaleform/menus/stats_inventory_menu.h
	src/scaleform/menus/stats_menu.cpp
	src/scaleform/menus/stats_menu.h
	src/scaleform/scaleform.cpp
	src/scaleform/scaleform.h
	src/setting/config_setting.cpp
	src/setting/config_setting.h
	src/setting/data/champion_data.h
	src/setting/data/faction_data.h
	src/setting/data/menu_data.h
	src/setting/data/player_data.h
	src/setting/data/thane_data.h
	src/setting/game_setting.cpp
	src/setting/game_setting.h
	src/setting/ini_setting.h
	src/setting/input_setting.cpp
	src/setting/input_setting.h
	src/setting/key_setting.cpp
	src/setting/key_setting.h
	src/util/file.cpp
	src/util/file.h
	src/util/form.cpp
	src/util/form.h
	src/util/key_util.cpp
	src/util/key_util.h
	src/util/player/perkvisitor.cpp
	src/util/player/perkvisitor.h
	src/util/player/player.cpp
	src/util/player/player.h
	src/util/quest/quest.cpp
	src/util/quest/quest.h
	src/util/type_util.cpp
	src/util/type_util.h
)
