set(sources ${sources}
	src/CLIK/Array.h
	src/CLIK/GFx/Controls/CoreList.h
	src/CLIK/GFx/Controls/ScrollingList.h
	src/CLIK/GFx/Core/UIComponent.h
	src/CLIK/MovieClip.h
	src/CLIK/Object.h
	src/CLIK/TextField.h
	src/PCH.h
	src/constants.h
	src/data/factiondata.h
	src/data/playerdata.h
	src/events.cpp
	src/events.h
	src/main.cpp
	src/scaleform/factionmenu.h
	src/scaleform/scaleform.cpp
	src/scaleform/scaleform.h
	src/scaleform/statsmenu.h
	src/settings/gamesettings.h
	src/settings/settings.h
	src/showhandler.h
	src/stats/champion.h
	src/stats/faction.h
	src/stats/factionfiller.h
	src/stats/factionholder.h
	src/stats/statfiller.h
	src/stats/statholder.h
	src/stats/thane.h
	src/utils.h
)
